import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { ArrowRight, Check, ChevronDown, Clock3, Mail, Menu, Phone, ShieldCheck, Sparkles, X } from 'lucide-react'
import { nav, services, site } from './config/site'

type LinkProps = { href: string; children: ReactNode; className?: string; onClick?: () => void }
const Link = ({ href, children, className = '', onClick }: LinkProps) => <a className={className} href={href} onClick={onClick}>{children}</a>
const Cta = ({ href = '/book', children, tone = 'primary' }: { href?: string; children: ReactNode; tone?: 'primary' | 'dark' | 'outline' }) => <Link href={href} className={`btn btn-${tone}`}>{children}<ArrowRight size={16}/></Link>

function Logo() { return <Link href="/" className="flex items-center gap-2.5" aria-label="Fortis AI home"><span className="grid h-9 w-9 place-items-center rounded-xl bg-teal text-lg font-black text-ink">F</span><span className="text-lg font-extrabold tracking-tight">FORTIS <span className="font-medium text-teal">AI</span></span></Link> }

function Header() {
  const [open, setOpen] = useState(false)
  return <header className="sticky top-0 z-50 border-b border-white/10 bg-ink/96 text-white backdrop-blur"><div className="container flex h-[76px] items-center justify-between"><Logo/><nav className="hidden items-center gap-6 text-sm text-slate-200 lg:flex">{nav.map(n => <Link href={n.href} key={n.href} className="transition hover:text-teal">{n.label}</Link>)}</nav><div className="hidden lg:block"><Cta href="/book">Book a discovery call</Cta></div><button aria-label="Toggle navigation" aria-expanded={open} onClick={() => setOpen(!open)} className="lg:hidden">{open ? <X/> : <Menu/>}</button></div>{open && <div className="border-t border-white/10 bg-ink lg:hidden"><nav className="container flex flex-col py-5 text-sm">{[...nav, { label: 'Contact', href: '/contact' }].map(n => <Link key={n.href} href={n.href} onClick={() => setOpen(false)} className="border-b border-white/10 py-3 text-slate-100">{n.label}</Link>)}<Cta href="/book">Book a discovery call</Cta></nav></div>}</header>
}

function Footer() { return <footer className="bg-ink py-14 text-slate-300"><div className="container grid gap-10 md:grid-cols-[1.6fr_1fr_1fr]"><div><Logo/><p className="mt-5 max-w-sm text-sm leading-6">Practical AI implementation and automation for Australian businesses. Fortis AI is a trading division of {site.legalEntity}.</p><p className="mt-5 text-sm">{site.email}<br/>{site.phone}</p></div><div><p className="text-xs font-bold uppercase tracking-widest text-teal">Explore</p><div className="mt-4 grid gap-2 text-sm">{nav.map(x => <Link key={x.href} href={x.href} className="hover:text-white">{x.label}</Link>)}<Link href="/contact">Contact</Link></div></div><div><p className="text-xs font-bold uppercase tracking-widest text-teal">Legal</p><div className="mt-4 grid gap-2 text-sm"><Link href="/privacy">Privacy policy</Link><Link href="/terms">Website terms</Link><Link href="/ai-services-terms">AI services terms</Link><Link href="/disclaimer">Disclaimer</Link><Link href="/cookies">Cookie policy</Link><Link href="/accessibility">Accessibility</Link></div></div></div><div className="container mt-12 border-t border-white/10 pt-6 text-xs text-slate-500">© {new Date().getFullYear()} {site.legalEntity}. ABN {site.abn}. All rights reserved.</div></footer> }

function Layout({ children }: { children: ReactNode }) { return <><Header/><main>{children}</main><Footer/></> }
function Intro({ eyebrow, title, body }: { eyebrow: string; title: string; body: string }) { return <section className="bg-ink py-20 text-white"><div className="container max-w-4xl"><p className="eyebrow text-teal">{eyebrow}</p><h1 className="display mt-4 text-5xl font-semibold md:text-7xl">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">{body}</p></div></section> }

const Section = ({ children, className = '' }: { children: ReactNode; className?: string }) => <section className={`py-16 md:py-24 ${className}`}><div className="container">{children}</div></section>

function Home() { return <Layout><section className="relative overflow-hidden bg-ink py-22 text-white md:py-30"><div className="dot-grid absolute inset-0 opacity-40"/><div className="container relative grid items-center gap-12 lg:grid-cols-[1.15fr_.85fr]"><div><p className="eyebrow text-teal">AI implementation · Australia-wide</p><h1 className="display mt-5 max-w-3xl text-6xl font-semibold md:text-8xl">Put AI to work in your business.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-300">Fortis AI helps Australian businesses identify practical opportunities for AI and automation, implement the right solutions and improve the way work gets done.</p><div className="mt-9 flex flex-wrap gap-3"><Cta href="/book">Book an AI discovery call</Cta><Cta href="/services" tone="outline">Explore AI services</Cta></div><p className="mt-8 flex items-center gap-2 text-sm text-slate-300"><Check className="text-teal" size={17}/>100% remote implementation across Australia</p></div><div className="relative rounded-[2rem] border border-white/12 bg-white/6 p-6 backdrop-blur"><p className="text-xs font-bold uppercase tracking-[.16em] text-teal">A business-first approach</p><div className="mt-8 space-y-4">{['Your processes', 'Practical opportunity', 'Working implementation', 'Human-led adoption'].map((t,i) => <div className="flex items-center gap-4" key={t}><span className="grid h-9 w-9 place-items-center rounded-full bg-teal text-sm font-bold text-ink">0{i+1}</span><span className="font-medium">{t}</span>{i < 3 && <span className="ml-auto text-teal">↘</span>}</div>)}</div><p className="mt-8 border-t border-white/12 pt-5 text-sm leading-6 text-slate-300">We don't start by asking which tool you want. We start by understanding how your business works.</p></div></div></section>
<Section><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">The difference</p><h2 className="display mt-3 text-4xl font-semibold md:text-5xl">Your business doesn't need more AI. It needs the right AI.</h2></div><div className="grid gap-4 sm:grid-cols-2">{['Where AI will actually help','Which processes should remain human-led','How your existing systems should connect','How to handle data thoughtfully'].map(x => <div className="card p-6" key={x}><Sparkles className="text-teal"/><p className="mt-6 font-semibold">{x}</p></div>)}</div></div></Section>
<Section className="bg-mist"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">Services</p><h2 className="display mt-3 text-4xl font-semibold md:text-5xl">From opportunity to operation.</h2></div><Cta href="/pricing" tone="outline">View pricing</Cta></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{services.map((s,i) => <Link href={s.href} key={s.title} className="card group p-6 transition hover:-translate-y-1"><p className="text-xs font-bold text-teal">0{i+1}</p><h3 className="mt-6 text-xl font-semibold">{s.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{s.body}</p><p className="mt-6 font-bold">{s.price}</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-bold">Explore <ArrowRight size={15} className="transition group-hover:translate-x-1"/></span></Link>)}</div></Section>
<Section><div className="grid gap-12 lg:grid-cols-[1fr_.95fr]"><div><p className="eyebrow">Practical applications</p><h2 className="display mt-3 text-4xl font-semibold md:text-5xl">What can AI actually do for your business?</h2><p className="mt-6 max-w-xl leading-7 text-slate-600">From reducing repetitive administration to making information easier to use, the right workflow starts with a clear business need.</p></div><div className="grid gap-3 sm:grid-cols-2">{[['Email & enquiries','Classify incoming work, extract key information and route it to the right person.'],['Document processing','Turn information in documents into structured, usable data.'],['Lead management','Qualify enquiries, update your CRM and create the right follow-up.'],['Meeting intelligence','Turn conversations into summaries, decisions and actions.'],['Reporting','Create structured management summaries from business data.'],['Internal knowledge','Help employees locate approved company information.']].map(([a,b]) => <div className="border-l-2 border-teal bg-white p-5" key={a}><h3 className="font-bold">{a}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{b}</p></div>)}</div></div><p className="mt-9 text-sm text-slate-500">Actual suitability depends on your processes, systems, data and business requirements.</p></Section>
<Section className="bg-ink text-white"><div className="grid gap-10 lg:grid-cols-[1fr_1.2fr]"><div><p className="eyebrow text-teal">How we work</p><h2 className="display mt-3 text-4xl font-semibold md:text-5xl">A clear path to practical change.</h2><p className="mt-6 max-w-md leading-7 text-slate-300">The FORTIS AI™ framework keeps the focus on better business operations—before, during and after implementation.</p></div><ol className="grid gap-4 sm:grid-cols-5">{['Discover','Assess','Design','Implement','Optimise'].map((x,i) => <li className="border-t border-teal/60 pt-4" key={x}><span className="text-xs font-bold text-teal">0{i+1}</span><p className="mt-3 font-bold">{x}</p></li>)}</ol></div></Section>
<Section><div className="card grid overflow-hidden lg:grid-cols-[1.05fr_.95fr]"><div className="p-8 md:p-12"><p className="eyebrow">Responsible AI</p><h2 className="display mt-3 text-4xl font-semibold">Practical AI must also be responsible AI.</h2><p className="mt-6 leading-7 text-slate-600">We consider appropriate data use, human oversight, access controls, testing, documentation and monitoring as part of a practical implementation—not as an afterthought.</p><div className="mt-8"><Cta href="/responsible-ai" tone="dark">Our approach to responsible AI</Cta></div></div><div className="bg-mist p-8 md:p-12"><ShieldCheck className="h-10 w-10 text-teal"/><div className="mt-8 grid grid-cols-2 gap-4 text-sm font-semibold">{['Human oversight','Data minimisation','Clear workflows','Ongoing monitoring'].map(x => <div className="rounded-xl border border-ink/10 bg-white p-4" key={x}>{x}</div>)}</div></div></div></Section>
<section className="bg-teal py-16"><div className="container flex flex-col items-start justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow text-ink/70">Start with a conversation</p><h2 className="display mt-3 max-w-2xl text-5xl font-semibold">Find out where AI could make a difference in your business.</h2></div><div className="flex flex-wrap gap-3"><Cta href="/book" tone="dark">Book a discovery call</Cta><Cta href="/ai-opportunity-audit" tone="outline">Request an audit</Cta></div></div></section></Layout> }

const serviceDetails: Record<string, { eyebrow: string; title: string; intro: string; price: string; includes: string[]; cta: string }> = {
  '/ai-opportunity-audit': { eyebrow: 'AI Opportunity Audit', title: 'Find the work AI can genuinely improve.', intro: 'A practical, remote assessment for Australian businesses that want to move beyond generic AI advice.', price: '$495 + GST', includes: ['A review of relevant processes, systems and administration','Approximately 5–10 practical AI and automation opportunities','Prioritised recommendations and technology considerations','Risk considerations and clear next steps'], cta: 'Book your AI Opportunity Audit' },
  '/ai-automation': { eyebrow: 'AI Automation & Implementation', title: 'Turn a useful idea into a working workflow.', intro: 'We design, build, integrate and test practical workflows around your business outcome—not a technology demo.', price: 'From $2,500 + GST', includes: ['Process discovery and workflow design','Integration with relevant business systems','Implementation, testing and deployment','Staff handover and practical documentation'], cta: 'Discuss your automation' },
  '/transformation-sprint': { eyebrow: 'AI Business Transformation Sprint', title: 'A focused path from opportunity to implementation.', intro: 'A structured 2–3 week engagement for businesses ready to implement one to three priority workflows.', price: '$4,950 + GST', includes: ['Week 1: discovery, assessment and workflow design','Week 2: build and integration','Week 3: testing, training and optimisation','Clear scope agreed before commencement'], cta: 'Book a transformation discussion' },
  '/ai-operations': { eyebrow: 'AI Operations Partner', title: 'Keep improving the systems that support your team.', intro: 'Ongoing support for businesses that want their AI and automation workflows monitored, maintained and improved.', price: 'From $995 + GST/month', includes: ['Workflow monitoring and troubleshooting','Optimisation and platform updates','Staff support and documentation','Monthly review and new opportunity recommendations'], cta: 'Talk about ongoing AI support' },
}

function ServicePage({ detail }: { detail: typeof serviceDetails[string] }) { return <Layout><Intro eyebrow={detail.eyebrow} title={detail.title} body={detail.intro}/><Section><div className="grid gap-12 lg:grid-cols-[1.15fr_.85fr]"><div><p className="eyebrow">What is included</p><h2 className="mt-3 text-3xl font-semibold">Designed around the way your business works.</h2><div className="mt-8 grid gap-4">{detail.includes.map(x => <div className="flex gap-3 border-b border-ink/10 pb-4" key={x}><Check className="mt-1 shrink-0 text-teal" size={18}/><p>{x}</p></div>)}</div><h2 className="mt-12 text-2xl font-semibold">What happens next</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">We begin by understanding your objective, existing processes and constraints. Scope, systems, data handling and responsibilities are confirmed before implementation begins.</p></div><aside className="card h-fit p-7 lg:sticky lg:top-26"><p className="eyebrow">Investment</p><p className="mt-3 text-3xl font-bold">{detail.price}</p><p className="mt-4 text-sm leading-6 text-slate-600">Pricing is indicative and may vary depending on scope, integrations, complexity and business requirements.</p><div className="mt-7"><Cta href="/book" tone="dark">{detail.cta}</Cta></div></aside></div></Section><Faq/></Layout> }

function Faq() { const [open, setOpen] = useState<number | null>(0); const qs = [['Do we need to know which AI tool to use?', 'No. We start with your business process and select an appropriate approach based on the outcome, systems and constraints.'],['Can this be delivered remotely?', 'Many engagements can be delivered remotely through secure online consultation and collaboration across Australia.'],['Will AI replace our team?', 'The objective is usually to reduce repetitive work and support better decisions, with people remaining responsible where their judgement matters.']]; return <Section className="bg-mist"><p className="eyebrow">Questions</p><h2 className="mt-3 text-3xl font-semibold">Frequently asked questions</h2><div className="mt-7 max-w-3xl">{qs.map(([q,a],i) => <div className="border-b border-ink/15" key={q}><button onClick={() => setOpen(open===i ? null : i)} className="flex w-full items-center justify-between py-5 text-left font-semibold">{q}<ChevronDown className={open===i ? 'rotate-180 transition' : 'transition'} size={18}/></button>{open===i && <p className="pb-5 leading-7 text-slate-600">{a}</p>}</div>)}</div></Section> }

function Services() { return <Layout><Intro eyebrow="AI services" title="Practical AI implementation, built around your business." body="Clear, outcome-focused services for Australian businesses that want to turn AI interest into useful operational improvement."/><Section><div className="grid gap-6 md:grid-cols-2">{services.map(s => <Link href={s.href} className="card group p-8 transition hover:-translate-y-1" key={s.title}><p className="eyebrow">{s.price}</p><h2 className="mt-3 text-2xl font-semibold">{s.title}</h2><p className="mt-4 leading-7 text-slate-600">{s.body}</p><span className="mt-7 inline-flex gap-2 text-sm font-bold">Explore the service <ArrowRight size={16}/></span></Link>)}</div></Section><Section className="bg-mist"><p className="eyebrow">How implementation works</p><h2 className="mt-3 max-w-2xl text-4xl font-semibold">Business problem → workflow → practical implementation.</h2><p className="mt-5 max-w-2xl leading-7 text-slate-600">We examine the work, identify what is appropriate to automate, design the right path and support your team through implementation.</p></Section></Layout> }

function Industries() { const list = [['Professional services','Proposals, CRM workflows, meeting notes and client onboarding.'],['Accounting','Document handling, client communications, reporting and onboarding.'],['Legal & legal-support','Intake administration, document workflows and knowledge retrieval.'],['Construction & trades','Enquiries, quote preparation, customer reminders and follow-up.'],['Property','Lead qualification, inspection follow-up and CRM updates.'],['Recruitment','Candidate administration, communications and meeting summaries.'],['Training & education','Learner communications, administration and knowledge workflows.'],['Childcare','Enquiry management, staff documentation and administrative reporting.'],['Healthcare administration','Administration, documents and non-clinical workflows.'],['Financial-services support','Process documentation, reporting and operational coordination.']]; return <Layout><Intro eyebrow="Industries" title="AI should fit the work—not force the work to fit the technology." body="Fortis AI works across Australian service businesses where practical, human-led automation can reduce administrative friction."/><Section><div className="grid gap-4 md:grid-cols-2">{list.map(([a,b],i) => <article className="card p-6" key={a}><span className="text-sm font-bold text-teal">0{i+1}</span><h2 className="mt-4 text-xl font-semibold">{a}</h2><p className="mt-3 leading-7 text-slate-600">{b}</p></article>)}</div><p className="mt-10 max-w-3xl text-sm leading-6 text-slate-500">Examples describe potential operational applications only. Suitable use, data handling and implementation requirements vary by business and must be assessed in context.</p></Section></Layout> }

function Methodology() { const steps = [['Discover','Understand your people, systems, processes and operational objectives.'],['Assess','Identify where AI and automation can create useful, appropriate value.'],['Design','Create a workflow that fits the real business outcome.'],['Implement','Build, integrate, test and deploy the agreed solution.'],['Optimise','Monitor, improve and extend the system as business needs evolve.']]; return <Layout><Intro eyebrow="FORTIS AI™ framework" title="We don't start with AI. We start with your business." body="A practical five-step framework to turn process insight into a working, manageable improvement."/><Section><div className="mx-auto max-w-4xl">{steps.map(([a,b],i) => <div className="grid gap-4 border-t border-ink/15 py-8 md:grid-cols-[100px_1fr_1.7fr]" key={a}><p className="text-xl font-bold text-teal">0{i+1}</p><h2 className="text-2xl font-semibold">{a}</h2><p className="leading-7 text-slate-600">{b}</p></div>)}</div></Section></Layout> }

function ResponsibleAI() { return <Layout><Intro eyebrow="Responsible AI" title="Useful AI should be designed with care." body="Responsible implementation is part of building a practical solution—not an extra layer added afterwards."/><Section><div className="grid gap-5 md:grid-cols-2">{[['Human oversight','Keep people responsible for important judgement, approvals and consequential decisions.'],['Appropriate data use','Consider what information is needed, where it goes and whether it should be used.'],['Clear workflows','Document the workflow, handover points and the responsibility for managing it.'],['Testing and monitoring','Test before deployment and review performance as systems and business needs change.'],['Transparency','Help relevant people understand where AI supports a process and how it is used.'],['Practical controls','Consider access, permissions and the safeguards appropriate for the business context.']].map(([a,b]) => <article className="card p-7" key={a}><ShieldCheck className="text-teal"/><h2 className="mt-6 text-xl font-semibold">{a}</h2><p className="mt-3 leading-7 text-slate-600">{b}</p></article>)}</div><p className="mt-10 max-w-3xl text-sm leading-6 text-slate-500">This information is general and does not constitute legal, privacy, cybersecurity or compliance advice. Requirements should be assessed with suitable professional advisers where needed.</p></Section></Layout> }

function Pricing() { return <Layout><Intro eyebrow="Pricing" title="Clear starting points for practical AI work." body="Transparent pricing makes it easier to decide on an appropriate first step. Final scope depends on your systems, requirements and complexity."/><Section><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{services.map(s => <div className="card flex flex-col p-7" key={s.title}><h2 className="text-xl font-semibold">{s.title}</h2><p className="mt-4 text-2xl font-bold">{s.price}</p><p className="mt-5 flex-1 text-sm leading-6 text-slate-600">{s.body}</p><div className="mt-8"><Cta href={s.href} tone="dark">Learn more</Cta></div></div>)}</div><p className="mt-9 text-sm text-slate-500">All prices are in Australian dollars and exclude GST unless otherwise stated. Pricing is indicative and may vary depending on scope, integrations, complexity and business requirements.</p></Section></Layout> }

function About() { return <Layout><Intro eyebrow="About Fortis AI" title="Business understanding, applied through practical technology." body="Fortis AI helps Australian businesses move from AI interest to useful implementation without losing sight of how the work actually gets done."/><Section><div className="grid gap-12 lg:grid-cols-2"><div><p className="eyebrow">Our perspective</p><h2 className="mt-3 text-3xl font-semibold">Technology should serve the business—not the other way around.</h2><p className="mt-6 leading-7 text-slate-600">Fortis AI is built on a business-first perspective shaped by operations, investigations, research, intelligence, risk assessment, reporting and process improvement. The aim is to identify meaningful opportunities and turn them into maintainable workflows.</p></div><div className="rounded-3xl bg-mist p-8"><p className="eyebrow">Australia-wide</p><h2 className="mt-3 text-2xl font-semibold">Remote implementation, grounded in practical collaboration.</h2><p className="mt-5 leading-7 text-slate-600">Fortis AI is a trading division of {site.legalEntity}. We work remotely with businesses throughout Australia using online consultation, collaborative design and cloud-based implementation where appropriate.</p></div></div></Section></Layout> }

function ContactForm({ audit = false }: { audit?: boolean }) { const name = audit ? 'ai-opportunity-audit' : 'contact'; const [status, setStatus] = useState<'idle' | 'sending' | 'success' | 'error'>('idle'); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; if (!form.reportValidity()) return; setStatus('sending'); try { const response = await fetch('/', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams(new FormData(form) as unknown as Record<string, string>).toString() }); if (!response.ok) throw new Error('Submission failed'); setStatus('success'); form.reset(); } catch { setStatus('error'); } }; if (status === 'success') return <div className="card p-8" role="status"><Check className="h-9 w-9 rounded-full bg-teal p-2 text-ink"/><h2 className="mt-5 text-2xl font-semibold">Thank you—your enquiry has been received.</h2><p className="mt-3 leading-7 text-slate-600">We will review your message and respond using the details you provided.</p></div>; return <form name={name} method="POST" data-netlify="true" data-netlify-honeypot="bot-field" onSubmit={submit} className="card p-6 md:p-8"><input type="hidden" name="form-name" value={name}/><p className="honeypot" aria-hidden="true"><label>Do not fill this out: <input name="bot-field" tabIndex={-1}/></label></p><div className="grid gap-5 sm:grid-cols-2"><Field label="Name" name="name" required/><Field label="Business name" name="business" required/><Field label="Email" name="email" type="email" required/><Field label="Phone" name="phone" type="tel"/></div>{audit && <div className="mt-5"><Field label="What would you most like to improve?" name="objective" textarea required/></div>}<div className="mt-5"><Field label="Tell us a little about your enquiry" name="message" textarea required/></div><p className="mt-5 text-xs leading-5 text-slate-500">Please do not include sensitive personal, financial, health, or confidential information in this form.</p>{status === 'error' && <p role="alert" className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-900">Your message could not be sent. Please try again or contact us by email or phone.</p>}<button disabled={status === 'sending'} type="submit" className="btn btn-dark mt-6 disabled:cursor-wait disabled:opacity-60">{status === 'sending' ? 'Sending…' : 'Send enquiry'} <ArrowRight size={16}/></button></form> }
function Field({ label, name, type='text', textarea = false, required = false }: { label: string; name: string; type?: string; textarea?: boolean; required?: boolean }) { return <label className="grid gap-2 text-sm font-semibold">{label}{textarea ? <textarea required={required} name={name} rows={5} className="rounded-xl border border-ink/20 bg-white px-3 py-3 font-normal outline-none ring-teal focus:ring-2"/> : <input required={required} type={type} name={name} className="rounded-xl border border-ink/20 bg-white px-3 py-3 font-normal outline-none ring-teal focus:ring-2"/>}</label> }
function Contact({ audit = false }: { audit?: boolean }) { return <Layout><Intro eyebrow={audit ? 'AI Opportunity Audit' : 'Contact Fortis AI'} title={audit ? 'Request an AI Opportunity Audit.' : 'Start with a practical conversation.'} body={audit ? 'Tell us about the operational work you would like to improve. We will use the information to understand whether an audit is a suitable next step.' : 'Talk with us about where administrative work is creating friction and where AI or automation may be useful.'}/><Section><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><aside><p className="eyebrow">Contact</p><h2 className="mt-3 text-3xl font-semibold">Let’s understand the work first.</h2><p className="mt-5 leading-7 text-slate-600">We work remotely with businesses across Australia. A short conversation is often the right way to clarify the opportunity.</p><div className="mt-8 grid gap-4 text-sm"><a className="flex gap-3" href={`mailto:${site.email}`}><Mail className="text-teal"/> {site.email}</a><a className="flex gap-3" href={`tel:${site.phone.replaceAll(' ','')}`}><Phone className="text-teal"/> {site.phone}</a><p className="flex gap-3"><Clock3 className="text-teal"/>100% remote implementation across Australia</p></div></aside><ContactForm audit={audit}/></div></Section></Layout> }

function Book() { return <Layout><Intro eyebrow="Book a discovery call" title="A practical starting point for your AI questions." body="Use the booking link to choose a suitable time, or contact us directly if you prefer."/><Section><div className="mx-auto max-w-2xl text-center"><div className="card p-10"><Clock3 className="mx-auto h-9 w-9 text-teal"/><h2 className="mt-6 text-3xl font-semibold">Book an AI discovery call</h2><p className="mt-4 leading-7 text-slate-600">We will discuss how your business works, where time is being lost, and whether an AI Opportunity Audit or another service is a sensible next step.</p><div className="mt-8">{site.bookingUrl === '#book' ? <Cta href="/contact" tone="dark">Contact us to book</Cta> : <a className="btn btn-dark" target="_blank" rel="noreferrer" href={site.bookingUrl}>Open booking calendar <ArrowRight size={16}/></a>}</div><p className="mt-6 text-sm text-slate-500">Prefer email or phone? {site.email} · {site.phone}</p></div></div></Section></Layout> }

function ThankYou({ audit = false }: { audit?: boolean }) { return <Layout><Section className="py-32"><div className="mx-auto max-w-2xl text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-teal"><Check/></span><p className="eyebrow mt-7">Thank you</p><h1 className="display mt-3 text-5xl font-semibold">{audit ? 'Your audit enquiry has been received.' : 'Your message has been received.'}</h1><p className="mt-6 leading-7 text-slate-600">We will review your enquiry and respond using the details you provided. If your matter is time-sensitive, please email {site.email} or call {site.phone}.</p><div className="mt-8"><Cta href="/" tone="dark">Return home</Cta></div></div></Section></Layout> }

const legal: Record<string, { title: string; intro: string; sections: [string, string][] }> = {
  '/privacy': { title: 'Privacy Policy', intro: 'How Fortis AI and Fortis Analytica Pty Ltd handle personal information collected through this website.', sections: [['Information we collect','We may collect contact details and information you voluntarily provide through our enquiry forms or direct communications.'],['How we use information','We use information to respond to enquiries, provide requested services, administer our relationship and improve our website and services.'],['Sensitive information','Please do not provide sensitive personal information through website forms unless we have specifically requested it through an appropriate channel.'],['Contact','For privacy enquiries, contact info@fortisanalytica.com.au. This policy should be reviewed by an Australian legal professional before publication.']] },
  '/terms': { title: 'Website Terms of Use', intro: 'Terms applying to use of the Fortis AI website.', sections: [['General information','Website content is general information and is not tailored advice.'],['Acceptable use','You must not misuse the website, attempt unauthorised access or interfere with its operation.'],['Intellectual property','Website content and branding are owned by or licensed to Fortis Analytica Pty Ltd unless stated otherwise.'],['Updates','We may update these terms and website content from time to time.']] },
  '/ai-services-terms': { title: 'AI Services Terms', intro: 'General terms relating to Fortis AI services.', sections: [['Scope','Each engagement is subject to an agreed scope, fees, responsibilities and any specific service agreement.'],['Client responsibilities','Clients remain responsible for decisions, approvals, access and the accuracy of information they provide.'],['AI-assisted outputs','AI-assisted systems may require human review and monitoring. They are not a substitute for professional, legal, financial, medical or other specialist advice.'],['Professional review','This draft requires legal review before publication or use in client contracting.']] },
  '/disclaimer': { title: 'Website Disclaimer', intro: 'Important information about the scope of this website.', sections: [['No advice','Website content is general information only and does not constitute legal, privacy, cybersecurity, financial or compliance advice.'],['No guarantees','Fortis AI does not guarantee specific commercial outcomes, AI accuracy, availability, security or regulatory compliance.'],['External services','Third-party services and platforms are governed by their own terms and policies.']] },
  '/cookies': { title: 'Cookie Policy', intro: 'How this website may use cookies and similar technologies.', sections: [['What cookies are','Cookies are small files that may be stored on your device to help a website function or understand how it is used.'],['Your choices','You can manage cookies through browser settings.'],['Analytics','If analytics are enabled, this policy should be updated with the relevant provider and consent approach before launch.']] },
  '/accessibility': { title: 'Accessibility Statement', intro: 'Our commitment to making this website usable for as many people as possible.', sections: [['Our approach','We aim to use clear structure, readable content, keyboard-accessible controls and sufficient visual contrast.'],['Feedback','If you experience an accessibility barrier, contact info@fortisanalytica.com.au with details so we can consider an improvement.'],['Ongoing work','Accessibility is an ongoing process and we will continue to improve the site where practical.']] },
}
function Legal({ page }: { page: typeof legal[string] }) { return <Layout><Intro eyebrow="Fortis AI information" title={page.title} body={page.intro}/><Section><article className="mx-auto max-w-3xl"><p className="text-sm text-slate-500">Effective date: [INSERT BEFORE LAUNCH]</p>{page.sections.map(([h,b]) => <section className="mt-9" key={h}><h2 className="text-2xl font-semibold">{h}</h2><p className="mt-3 leading-7 text-slate-600">{b}</p></section>)}<div className="mt-12 rounded-xl border border-amber-300 bg-amber-50 p-5 text-sm leading-6 text-amber-950">Pre-launch requirement: Have this draft reviewed by a qualified Australian legal professional before publishing.</div></article></Section></Layout> }

function NotFound() { return <Layout><Section className="py-32"><p className="eyebrow">404</p><h1 className="display mt-4 text-6xl font-semibold">This page has moved on.</h1><p className="mt-6 max-w-lg leading-7 text-slate-600">The page you are looking for is not available. You can return home or get in touch with Fortis AI.</p><div className="mt-8 flex gap-3"><Cta href="/">Return home</Cta><Cta href="/contact" tone="outline">Contact us</Cta></div></Section></Layout> }

function App() { const path = window.location.pathname.replace(/\/$/, '') || '/'; const detail = serviceDetails[path]; useEffect(() => { const titles: Record<string,string> = {'/':'Fortis AI | Practical AI solutions for Australian business','/services':'AI Services | Fortis AI','/industries':'Industries | Fortis AI','/methodology':'Methodology | Fortis AI','/responsible-ai':'Responsible AI | Fortis AI','/pricing':'Pricing | Fortis AI','/about':'About Fortis AI','/contact':'Contact | Fortis AI','/book':'Book an AI Discovery Call | Fortis AI'}; const descriptions: Record<string,string> = {'/':'Practical AI implementation and automation for Australian businesses.','/services':'Explore practical AI implementation, automation and ongoing support services.','/industries':'Practical AI and automation applications for Australian service businesses.','/responsible-ai':'How Fortis AI approaches practical, responsible AI implementation.','/pricing':'Transparent starting prices for Fortis AI services.'}; const title = titles[path] || `${detail?.eyebrow || legal[path]?.title || 'Fortis AI'} | Fortis AI`; const description = descriptions[path] || detail?.intro || legal[path]?.intro || 'Practical AI implementation and automation for Australian businesses.'; document.title = title; document.querySelector('meta[name="description"]')?.setAttribute('content', description); document.querySelector('meta[property="og:title"]')?.setAttribute('content', title); document.querySelector('meta[property="og:description"]')?.setAttribute('content', description); document.querySelector('link[rel="canonical"]')?.setAttribute('href', `${site.url}${path === '/' ? '/' : path}`); }, [path, detail]); if(detail) return <ServicePage detail={detail}/>; if(path === '/') return <Home/>; if(path === '/services') return <Services/>; if(path === '/industries') return <Industries/>; if(path === '/methodology') return <Methodology/>; if(path === '/responsible-ai' || path === '/ai-data-use') return <ResponsibleAI/>; if(path === '/pricing') return <Pricing/>; if(path === '/about') return <About/>; if(path === '/contact') return <Contact/>; if(path === '/audit-enquiry') return <Contact audit/>; if(path === '/book') return <Book/>; if(path === '/audit-enquiry-thank-you') return <ThankYou audit/>; if(['/thank-you','/contact-thank-you'].includes(path)) return <ThankYou/>; if(legal[path]) return <Legal page={legal[path]}/>; return <NotFound/> }

export default App
